// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: converse/service/health/health.proto

#include "converse/service/health/health.pb.h"
#include "converse/service/health/health.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace converse {
namespace service {
namespace health {

static const char* HealthService_method_names[] = {
  "/converse.service.health.HealthService/HealthCheck",
};

std::unique_ptr< HealthService::Stub> HealthService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HealthService::Stub> stub(new HealthService::Stub(channel, options));
  return stub;
}

HealthService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_HealthCheck_(HealthService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HealthService::Stub::HealthCheck(::grpc::ClientContext* context, const ::converse::service::health::HealthCheckRequest& request, ::converse::service::health::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::converse::service::health::HealthCheckRequest, ::converse::service::health::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void HealthService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::converse::service::health::HealthCheckRequest* request, ::converse::service::health::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::converse::service::health::HealthCheckRequest, ::converse::service::health::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void HealthService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::converse::service::health::HealthCheckRequest* request, ::converse::service::health::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::converse::service::health::HealthCheckResponse>* HealthService::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::converse::service::health::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::converse::service::health::HealthCheckResponse, ::converse::service::health::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::converse::service::health::HealthCheckResponse>* HealthService::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::converse::service::health::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

HealthService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HealthService::Service, ::converse::service::health::HealthCheckRequest, ::converse::service::health::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HealthService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::converse::service::health::HealthCheckRequest* req,
             ::converse::service::health::HealthCheckResponse* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
}

HealthService::Service::~Service() {
}

::grpc::Status HealthService::Service::HealthCheck(::grpc::ServerContext* context, const ::converse::service::health::HealthCheckRequest* request, ::converse::service::health::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace converse
}  // namespace service
}  // namespace health

