// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: converse/service/link/link.proto
// Protobuf C++ Version: 5.29.3

#ifndef converse_2fservice_2flink_2flink_2eproto_2epb_2eh
#define converse_2fservice_2flink_2flink_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_converse_2fservice_2flink_2flink_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_converse_2fservice_2flink_2flink_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_converse_2fservice_2flink_2flink_2eproto;
namespace converse {
namespace service {
namespace link {
class GetServersRequest;
struct GetServersRequestDefaultTypeInternal;
extern GetServersRequestDefaultTypeInternal _GetServersRequest_default_instance_;
class GetServersResponse;
struct GetServersResponseDefaultTypeInternal;
extern GetServersResponseDefaultTypeInternal _GetServersResponse_default_instance_;
class GetTransactionsRequest;
struct GetTransactionsRequestDefaultTypeInternal;
extern GetTransactionsRequestDefaultTypeInternal _GetTransactionsRequest_default_instance_;
class GetTransactionsResponse;
struct GetTransactionsResponseDefaultTypeInternal;
extern GetTransactionsResponseDefaultTypeInternal _GetTransactionsResponse_default_instance_;
class IdentifyMyselfRequest;
struct IdentifyMyselfRequestDefaultTypeInternal;
extern IdentifyMyselfRequestDefaultTypeInternal _IdentifyMyselfRequest_default_instance_;
class IdentifyMyselfResponse;
struct IdentifyMyselfResponseDefaultTypeInternal;
extern IdentifyMyselfResponseDefaultTypeInternal _IdentifyMyselfResponse_default_instance_;
class Operation;
struct OperationDefaultTypeInternal;
extern OperationDefaultTypeInternal _Operation_default_instance_;
class Operation_NewValuesEntry_DoNotUse;
struct Operation_NewValuesEntry_DoNotUseDefaultTypeInternal;
extern Operation_NewValuesEntry_DoNotUseDefaultTypeInternal _Operation_NewValuesEntry_DoNotUse_default_instance_;
class Operation_OldKeyValuesEntry_DoNotUse;
struct Operation_OldKeyValuesEntry_DoNotUseDefaultTypeInternal;
extern Operation_OldKeyValuesEntry_DoNotUseDefaultTypeInternal _Operation_OldKeyValuesEntry_DoNotUse_default_instance_;
class ServerAddress;
struct ServerAddressDefaultTypeInternal;
extern ServerAddressDefaultTypeInternal _ServerAddress_default_instance_;
}  // namespace link
}  // namespace service
}  // namespace converse
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace converse {
namespace service {
namespace link {
enum OperationType : int {
  OPERATION_TYPE_UNSPECIFIED = 0,
  OPERATION_TYPE_INSERT = 1,
  OPERATION_TYPE_UPDATE = 2,
  OperationType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  OperationType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool OperationType_IsValid(int value);
extern const uint32_t OperationType_internal_data_[];
constexpr OperationType OperationType_MIN = static_cast<OperationType>(0);
constexpr OperationType OperationType_MAX = static_cast<OperationType>(2);
constexpr int OperationType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
OperationType_descriptor();
template <typename T>
const std::string& OperationType_Name(T value) {
  static_assert(std::is_same<T, OperationType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to OperationType_Name().");
  return OperationType_Name(static_cast<OperationType>(value));
}
template <>
inline const std::string& OperationType_Name(OperationType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<OperationType_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool OperationType_Parse(absl::string_view name, OperationType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OperationType>(
      OperationType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class ServerAddress final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:converse.service.link.ServerAddress) */ {
 public:
  inline ServerAddress() : ServerAddress(nullptr) {}
  ~ServerAddress() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ServerAddress* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ServerAddress));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ServerAddress(
      ::google::protobuf::internal::ConstantInitialized);

  inline ServerAddress(const ServerAddress& from) : ServerAddress(nullptr, from) {}
  inline ServerAddress(ServerAddress&& from) noexcept
      : ServerAddress(nullptr, std::move(from)) {}
  inline ServerAddress& operator=(const ServerAddress& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerAddress& operator=(ServerAddress&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerAddress& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerAddress* internal_default_instance() {
    return reinterpret_cast<const ServerAddress*>(
        &_ServerAddress_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ServerAddress& a, ServerAddress& b) { a.Swap(&b); }
  inline void Swap(ServerAddress* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerAddress* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerAddress* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ServerAddress>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ServerAddress& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ServerAddress& from) { ServerAddress::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ServerAddress* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "converse.service.link.ServerAddress"; }

 protected:
  explicit ServerAddress(::google::protobuf::Arena* arena);
  ServerAddress(::google::protobuf::Arena* arena, const ServerAddress& from);
  ServerAddress(::google::protobuf::Arena* arena, ServerAddress&& from) noexcept
      : ServerAddress(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHostFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // string host = 1 [json_name = "host"];
  void clear_host() ;
  const std::string& host() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_host(Arg_&& arg, Args_... args);
  std::string* mutable_host();
  PROTOBUF_NODISCARD std::string* release_host();
  void set_allocated_host(std::string* value);

  private:
  const std::string& _internal_host() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_host(
      const std::string& value);
  std::string* _internal_mutable_host();

  public:
  // uint32 port = 2 [json_name = "port"];
  void clear_port() ;
  ::uint32_t port() const;
  void set_port(::uint32_t value);

  private:
  ::uint32_t _internal_port() const;
  void _internal_set_port(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:converse.service.link.ServerAddress)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      48, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ServerAddress& from_msg);
    ::google::protobuf::internal::ArenaStringPtr host_;
    ::uint32_t port_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;
};
// -------------------------------------------------------------------

class Operation_OldKeyValuesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  Operation_OldKeyValuesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Operation_OldKeyValuesEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit Operation_OldKeyValuesEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const Operation_OldKeyValuesEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const Operation_OldKeyValuesEntry_DoNotUse*>(
        &_Operation_OldKeyValuesEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      66, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class Operation_NewValuesEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          std::string, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      std::string, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  Operation_NewValuesEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Operation_NewValuesEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit Operation_NewValuesEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const Operation_NewValuesEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const Operation_NewValuesEntry_DoNotUse*>(
        &_Operation_NewValuesEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      63, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class IdentifyMyselfRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:converse.service.link.IdentifyMyselfRequest) */ {
 public:
  inline IdentifyMyselfRequest() : IdentifyMyselfRequest(nullptr) {}
  ~IdentifyMyselfRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IdentifyMyselfRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IdentifyMyselfRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR IdentifyMyselfRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline IdentifyMyselfRequest(const IdentifyMyselfRequest& from) : IdentifyMyselfRequest(nullptr, from) {}
  inline IdentifyMyselfRequest(IdentifyMyselfRequest&& from) noexcept
      : IdentifyMyselfRequest(nullptr, std::move(from)) {}
  inline IdentifyMyselfRequest& operator=(const IdentifyMyselfRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline IdentifyMyselfRequest& operator=(IdentifyMyselfRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IdentifyMyselfRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const IdentifyMyselfRequest* internal_default_instance() {
    return reinterpret_cast<const IdentifyMyselfRequest*>(
        &_IdentifyMyselfRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(IdentifyMyselfRequest& a, IdentifyMyselfRequest& b) { a.Swap(&b); }
  inline void Swap(IdentifyMyselfRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IdentifyMyselfRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IdentifyMyselfRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IdentifyMyselfRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IdentifyMyselfRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IdentifyMyselfRequest& from) { IdentifyMyselfRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IdentifyMyselfRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "converse.service.link.IdentifyMyselfRequest"; }

 protected:
  explicit IdentifyMyselfRequest(::google::protobuf::Arena* arena);
  IdentifyMyselfRequest(::google::protobuf::Arena* arena, const IdentifyMyselfRequest& from);
  IdentifyMyselfRequest(::google::protobuf::Arena* arena, IdentifyMyselfRequest&& from) noexcept
      : IdentifyMyselfRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHostFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // string host = 1 [json_name = "host"];
  void clear_host() ;
  const std::string& host() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_host(Arg_&& arg, Args_... args);
  std::string* mutable_host();
  PROTOBUF_NODISCARD std::string* release_host();
  void set_allocated_host(std::string* value);

  private:
  const std::string& _internal_host() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_host(
      const std::string& value);
  std::string* _internal_mutable_host();

  public:
  // uint32 port = 2 [json_name = "port"];
  void clear_port() ;
  ::uint32_t port() const;
  void set_port(::uint32_t value);

  private:
  ::uint32_t _internal_port() const;
  void _internal_set_port(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:converse.service.link.IdentifyMyselfRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      56, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const IdentifyMyselfRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr host_;
    ::uint32_t port_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;
};
// -------------------------------------------------------------------

class GetTransactionsRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:converse.service.link.GetTransactionsRequest) */ {
 public:
  inline GetTransactionsRequest() : GetTransactionsRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetTransactionsRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetTransactionsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetTransactionsRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetTransactionsRequest(const GetTransactionsRequest& from) : GetTransactionsRequest(nullptr, from) {}
  inline GetTransactionsRequest(GetTransactionsRequest&& from) noexcept
      : GetTransactionsRequest(nullptr, std::move(from)) {}
  inline GetTransactionsRequest& operator=(const GetTransactionsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetTransactionsRequest& operator=(GetTransactionsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetTransactionsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetTransactionsRequest* internal_default_instance() {
    return reinterpret_cast<const GetTransactionsRequest*>(
        &_GetTransactionsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(GetTransactionsRequest& a, GetTransactionsRequest& b) { a.Swap(&b); }
  inline void Swap(GetTransactionsRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetTransactionsRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetTransactionsRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<GetTransactionsRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const GetTransactionsRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const GetTransactionsRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "converse.service.link.GetTransactionsRequest"; }

 protected:
  explicit GetTransactionsRequest(::google::protobuf::Arena* arena);
  GetTransactionsRequest(::google::protobuf::Arena* arena, const GetTransactionsRequest& from);
  GetTransactionsRequest(::google::protobuf::Arena* arena, GetTransactionsRequest&& from) noexcept
      : GetTransactionsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:converse.service.link.GetTransactionsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetTransactionsRequest& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;
};
// -------------------------------------------------------------------

class GetServersRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:converse.service.link.GetServersRequest) */ {
 public:
  inline GetServersRequest() : GetServersRequest(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetServersRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetServersRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetServersRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetServersRequest(const GetServersRequest& from) : GetServersRequest(nullptr, from) {}
  inline GetServersRequest(GetServersRequest&& from) noexcept
      : GetServersRequest(nullptr, std::move(from)) {}
  inline GetServersRequest& operator=(const GetServersRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServersRequest& operator=(GetServersRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServersRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServersRequest* internal_default_instance() {
    return reinterpret_cast<const GetServersRequest*>(
        &_GetServersRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GetServersRequest& a, GetServersRequest& b) { a.Swap(&b); }
  inline void Swap(GetServersRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServersRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServersRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<GetServersRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const GetServersRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const GetServersRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "converse.service.link.GetServersRequest"; }

 protected:
  explicit GetServersRequest(::google::protobuf::Arena* arena);
  GetServersRequest(::google::protobuf::Arena* arena, const GetServersRequest& from);
  GetServersRequest(::google::protobuf::Arena* arena, GetServersRequest&& from) noexcept
      : GetServersRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:converse.service.link.GetServersRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetServersRequest& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;
};
// -------------------------------------------------------------------

class Operation final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:converse.service.link.Operation) */ {
 public:
  inline Operation() : Operation(nullptr) {}
  ~Operation() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Operation* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Operation));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Operation(
      ::google::protobuf::internal::ConstantInitialized);

  inline Operation(const Operation& from) : Operation(nullptr, from) {}
  inline Operation(Operation&& from) noexcept
      : Operation(nullptr, std::move(from)) {}
  inline Operation& operator=(const Operation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Operation& operator=(Operation&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Operation& default_instance() {
    return *internal_default_instance();
  }
  static inline const Operation* internal_default_instance() {
    return reinterpret_cast<const Operation*>(
        &_Operation_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 9;
  friend void swap(Operation& a, Operation& b) { a.Swap(&b); }
  inline void Swap(Operation* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Operation* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Operation* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Operation>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Operation& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Operation& from) { Operation::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Operation* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "converse.service.link.Operation"; }

 protected:
  explicit Operation(::google::protobuf::Arena* arena);
  Operation(::google::protobuf::Arena* arena, const Operation& from);
  Operation(::google::protobuf::Arena* arena, Operation&& from) noexcept
      : Operation(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNewValuesFieldNumber = 3,
    kOldKeyValuesFieldNumber = 4,
    kTableNameFieldNumber = 2,
    kTypeFieldNumber = 1,
  };
  // map<string, string> new_values = 3 [json_name = "newValues"];
  int new_values_size() const;
  private:
  int _internal_new_values_size() const;

  public:
  void clear_new_values() ;
  const ::google::protobuf::Map<std::string, std::string>& new_values() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_new_values();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_new_values() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_new_values();

  public:
  // map<string, string> old_key_values = 4 [json_name = "oldKeyValues"];
  int old_key_values_size() const;
  private:
  int _internal_old_key_values_size() const;

  public:
  void clear_old_key_values() ;
  const ::google::protobuf::Map<std::string, std::string>& old_key_values() const;
  ::google::protobuf::Map<std::string, std::string>* mutable_old_key_values();

  private:
  const ::google::protobuf::Map<std::string, std::string>& _internal_old_key_values() const;
  ::google::protobuf::Map<std::string, std::string>* _internal_mutable_old_key_values();

  public:
  // string table_name = 2 [json_name = "tableName"];
  void clear_table_name() ;
  const std::string& table_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_table_name(Arg_&& arg, Args_... args);
  std::string* mutable_table_name();
  PROTOBUF_NODISCARD std::string* release_table_name();
  void set_allocated_table_name(std::string* value);

  private:
  const std::string& _internal_table_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_table_name(
      const std::string& value);
  std::string* _internal_mutable_table_name();

  public:
  // .converse.service.link.OperationType type = 1 [json_name = "type"];
  void clear_type() ;
  ::converse::service::link::OperationType type() const;
  void set_type(::converse::service::link::OperationType value);

  private:
  ::converse::service::link::OperationType _internal_type() const;
  void _internal_set_type(::converse::service::link::OperationType value);

  public:
  // @@protoc_insertion_point(class_scope:converse.service.link.Operation)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 4, 2,
      74, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Operation& from_msg);
    ::google::protobuf::internal::MapField<Operation_NewValuesEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        new_values_;
    ::google::protobuf::internal::MapField<Operation_OldKeyValuesEntry_DoNotUse, std::string, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>
        old_key_values_;
    ::google::protobuf::internal::ArenaStringPtr table_name_;
    int type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;
};
// -------------------------------------------------------------------

class IdentifyMyselfResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:converse.service.link.IdentifyMyselfResponse) */ {
 public:
  inline IdentifyMyselfResponse() : IdentifyMyselfResponse(nullptr) {}
  ~IdentifyMyselfResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IdentifyMyselfResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IdentifyMyselfResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR IdentifyMyselfResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline IdentifyMyselfResponse(const IdentifyMyselfResponse& from) : IdentifyMyselfResponse(nullptr, from) {}
  inline IdentifyMyselfResponse(IdentifyMyselfResponse&& from) noexcept
      : IdentifyMyselfResponse(nullptr, std::move(from)) {}
  inline IdentifyMyselfResponse& operator=(const IdentifyMyselfResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline IdentifyMyselfResponse& operator=(IdentifyMyselfResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IdentifyMyselfResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const IdentifyMyselfResponse* internal_default_instance() {
    return reinterpret_cast<const IdentifyMyselfResponse*>(
        &_IdentifyMyselfResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(IdentifyMyselfResponse& a, IdentifyMyselfResponse& b) { a.Swap(&b); }
  inline void Swap(IdentifyMyselfResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IdentifyMyselfResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IdentifyMyselfResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IdentifyMyselfResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IdentifyMyselfResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IdentifyMyselfResponse& from) { IdentifyMyselfResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IdentifyMyselfResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "converse.service.link.IdentifyMyselfResponse"; }

 protected:
  explicit IdentifyMyselfResponse(::google::protobuf::Arena* arena);
  IdentifyMyselfResponse(::google::protobuf::Arena* arena, const IdentifyMyselfResponse& from);
  IdentifyMyselfResponse(::google::protobuf::Arena* arena, IdentifyMyselfResponse&& from) noexcept
      : IdentifyMyselfResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClusterAddressesFieldNumber = 1,
    kDatabaseFieldNumber = 2,
  };
  // repeated .converse.service.link.ServerAddress cluster_addresses = 1 [json_name = "clusterAddresses"];
  int cluster_addresses_size() const;
  private:
  int _internal_cluster_addresses_size() const;

  public:
  void clear_cluster_addresses() ;
  ::converse::service::link::ServerAddress* mutable_cluster_addresses(int index);
  ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>* mutable_cluster_addresses();

  private:
  const ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>& _internal_cluster_addresses() const;
  ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>* _internal_mutable_cluster_addresses();
  public:
  const ::converse::service::link::ServerAddress& cluster_addresses(int index) const;
  ::converse::service::link::ServerAddress* add_cluster_addresses();
  const ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>& cluster_addresses() const;
  // bytes database = 2 [json_name = "database"];
  void clear_database() ;
  const std::string& database() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_database(Arg_&& arg, Args_... args);
  std::string* mutable_database();
  PROTOBUF_NODISCARD std::string* release_database();
  void set_allocated_database(std::string* value);

  private:
  const std::string& _internal_database() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_database(
      const std::string& value);
  std::string* _internal_mutable_database();

  public:
  // @@protoc_insertion_point(class_scope:converse.service.link.IdentifyMyselfResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const IdentifyMyselfResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::converse::service::link::ServerAddress > cluster_addresses_;
    ::google::protobuf::internal::ArenaStringPtr database_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;
};
// -------------------------------------------------------------------

class GetServersResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:converse.service.link.GetServersResponse) */ {
 public:
  inline GetServersResponse() : GetServersResponse(nullptr) {}
  ~GetServersResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetServersResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetServersResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetServersResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetServersResponse(const GetServersResponse& from) : GetServersResponse(nullptr, from) {}
  inline GetServersResponse(GetServersResponse&& from) noexcept
      : GetServersResponse(nullptr, std::move(from)) {}
  inline GetServersResponse& operator=(const GetServersResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServersResponse& operator=(GetServersResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServersResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServersResponse* internal_default_instance() {
    return reinterpret_cast<const GetServersResponse*>(
        &_GetServersResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(GetServersResponse& a, GetServersResponse& b) { a.Swap(&b); }
  inline void Swap(GetServersResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServersResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServersResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetServersResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetServersResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetServersResponse& from) { GetServersResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetServersResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "converse.service.link.GetServersResponse"; }

 protected:
  explicit GetServersResponse(::google::protobuf::Arena* arena);
  GetServersResponse(::google::protobuf::Arena* arena, const GetServersResponse& from);
  GetServersResponse(::google::protobuf::Arena* arena, GetServersResponse&& from) noexcept
      : GetServersResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClusterAddressesFieldNumber = 1,
  };
  // repeated .converse.service.link.ServerAddress cluster_addresses = 1 [json_name = "clusterAddresses"];
  int cluster_addresses_size() const;
  private:
  int _internal_cluster_addresses_size() const;

  public:
  void clear_cluster_addresses() ;
  ::converse::service::link::ServerAddress* mutable_cluster_addresses(int index);
  ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>* mutable_cluster_addresses();

  private:
  const ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>& _internal_cluster_addresses() const;
  ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>* _internal_mutable_cluster_addresses();
  public:
  const ::converse::service::link::ServerAddress& cluster_addresses(int index) const;
  ::converse::service::link::ServerAddress* add_cluster_addresses();
  const ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>& cluster_addresses() const;
  // @@protoc_insertion_point(class_scope:converse.service.link.GetServersResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetServersResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::converse::service::link::ServerAddress > cluster_addresses_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;
};
// -------------------------------------------------------------------

class GetTransactionsResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:converse.service.link.GetTransactionsResponse) */ {
 public:
  inline GetTransactionsResponse() : GetTransactionsResponse(nullptr) {}
  ~GetTransactionsResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetTransactionsResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetTransactionsResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetTransactionsResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetTransactionsResponse(const GetTransactionsResponse& from) : GetTransactionsResponse(nullptr, from) {}
  inline GetTransactionsResponse(GetTransactionsResponse&& from) noexcept
      : GetTransactionsResponse(nullptr, std::move(from)) {}
  inline GetTransactionsResponse& operator=(const GetTransactionsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetTransactionsResponse& operator=(GetTransactionsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetTransactionsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetTransactionsResponse* internal_default_instance() {
    return reinterpret_cast<const GetTransactionsResponse*>(
        &_GetTransactionsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(GetTransactionsResponse& a, GetTransactionsResponse& b) { a.Swap(&b); }
  inline void Swap(GetTransactionsResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetTransactionsResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetTransactionsResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetTransactionsResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetTransactionsResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetTransactionsResponse& from) { GetTransactionsResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetTransactionsResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "converse.service.link.GetTransactionsResponse"; }

 protected:
  explicit GetTransactionsResponse(::google::protobuf::Arena* arena);
  GetTransactionsResponse(::google::protobuf::Arena* arena, const GetTransactionsResponse& from);
  GetTransactionsResponse(::google::protobuf::Arena* arena, GetTransactionsResponse&& from) noexcept
      : GetTransactionsResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOperationsFieldNumber = 2,
    kTransactionIdFieldNumber = 1,
  };
  // repeated .converse.service.link.Operation operations = 2 [json_name = "operations"];
  int operations_size() const;
  private:
  int _internal_operations_size() const;

  public:
  void clear_operations() ;
  ::converse::service::link::Operation* mutable_operations(int index);
  ::google::protobuf::RepeatedPtrField<::converse::service::link::Operation>* mutable_operations();

  private:
  const ::google::protobuf::RepeatedPtrField<::converse::service::link::Operation>& _internal_operations() const;
  ::google::protobuf::RepeatedPtrField<::converse::service::link::Operation>* _internal_mutable_operations();
  public:
  const ::converse::service::link::Operation& operations(int index) const;
  ::converse::service::link::Operation* add_operations();
  const ::google::protobuf::RepeatedPtrField<::converse::service::link::Operation>& operations() const;
  // uint64 transaction_id = 1 [json_name = "transactionId"];
  void clear_transaction_id() ;
  ::uint64_t transaction_id() const;
  void set_transaction_id(::uint64_t value);

  private:
  ::uint64_t _internal_transaction_id() const;
  void _internal_set_transaction_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:converse.service.link.GetTransactionsResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetTransactionsResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::converse::service::link::Operation > operations_;
    ::uint64_t transaction_id_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_converse_2fservice_2flink_2flink_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GetServersRequest

// -------------------------------------------------------------------

// GetServersResponse

// repeated .converse.service.link.ServerAddress cluster_addresses = 1 [json_name = "clusterAddresses"];
inline int GetServersResponse::_internal_cluster_addresses_size() const {
  return _internal_cluster_addresses().size();
}
inline int GetServersResponse::cluster_addresses_size() const {
  return _internal_cluster_addresses_size();
}
inline void GetServersResponse::clear_cluster_addresses() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cluster_addresses_.Clear();
}
inline ::converse::service::link::ServerAddress* GetServersResponse::mutable_cluster_addresses(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:converse.service.link.GetServersResponse.cluster_addresses)
  return _internal_mutable_cluster_addresses()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>* GetServersResponse::mutable_cluster_addresses()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:converse.service.link.GetServersResponse.cluster_addresses)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cluster_addresses();
}
inline const ::converse::service::link::ServerAddress& GetServersResponse::cluster_addresses(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:converse.service.link.GetServersResponse.cluster_addresses)
  return _internal_cluster_addresses().Get(index);
}
inline ::converse::service::link::ServerAddress* GetServersResponse::add_cluster_addresses() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::converse::service::link::ServerAddress* _add = _internal_mutable_cluster_addresses()->Add();
  // @@protoc_insertion_point(field_add:converse.service.link.GetServersResponse.cluster_addresses)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>& GetServersResponse::cluster_addresses() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:converse.service.link.GetServersResponse.cluster_addresses)
  return _internal_cluster_addresses();
}
inline const ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>&
GetServersResponse::_internal_cluster_addresses() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cluster_addresses_;
}
inline ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>*
GetServersResponse::_internal_mutable_cluster_addresses() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cluster_addresses_;
}

// -------------------------------------------------------------------

// ServerAddress

// string host = 1 [json_name = "host"];
inline void ServerAddress::clear_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.ClearToEmpty();
}
inline const std::string& ServerAddress::host() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:converse.service.link.ServerAddress.host)
  return _internal_host();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ServerAddress::set_host(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:converse.service.link.ServerAddress.host)
}
inline std::string* ServerAddress::mutable_host() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_host();
  // @@protoc_insertion_point(field_mutable:converse.service.link.ServerAddress.host)
  return _s;
}
inline const std::string& ServerAddress::_internal_host() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.host_.Get();
}
inline void ServerAddress::_internal_set_host(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.Set(value, GetArena());
}
inline std::string* ServerAddress::_internal_mutable_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.host_.Mutable( GetArena());
}
inline std::string* ServerAddress::release_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:converse.service.link.ServerAddress.host)
  return _impl_.host_.Release();
}
inline void ServerAddress::set_allocated_host(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.host_.IsDefault()) {
    _impl_.host_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:converse.service.link.ServerAddress.host)
}

// uint32 port = 2 [json_name = "port"];
inline void ServerAddress::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0u;
}
inline ::uint32_t ServerAddress::port() const {
  // @@protoc_insertion_point(field_get:converse.service.link.ServerAddress.port)
  return _internal_port();
}
inline void ServerAddress::set_port(::uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:converse.service.link.ServerAddress.port)
}
inline ::uint32_t ServerAddress::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void ServerAddress::_internal_set_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// -------------------------------------------------------------------

// IdentifyMyselfRequest

// string host = 1 [json_name = "host"];
inline void IdentifyMyselfRequest::clear_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.ClearToEmpty();
}
inline const std::string& IdentifyMyselfRequest::host() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:converse.service.link.IdentifyMyselfRequest.host)
  return _internal_host();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void IdentifyMyselfRequest::set_host(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:converse.service.link.IdentifyMyselfRequest.host)
}
inline std::string* IdentifyMyselfRequest::mutable_host() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_host();
  // @@protoc_insertion_point(field_mutable:converse.service.link.IdentifyMyselfRequest.host)
  return _s;
}
inline const std::string& IdentifyMyselfRequest::_internal_host() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.host_.Get();
}
inline void IdentifyMyselfRequest::_internal_set_host(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.Set(value, GetArena());
}
inline std::string* IdentifyMyselfRequest::_internal_mutable_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.host_.Mutable( GetArena());
}
inline std::string* IdentifyMyselfRequest::release_host() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:converse.service.link.IdentifyMyselfRequest.host)
  return _impl_.host_.Release();
}
inline void IdentifyMyselfRequest::set_allocated_host(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.host_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.host_.IsDefault()) {
    _impl_.host_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:converse.service.link.IdentifyMyselfRequest.host)
}

// uint32 port = 2 [json_name = "port"];
inline void IdentifyMyselfRequest::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0u;
}
inline ::uint32_t IdentifyMyselfRequest::port() const {
  // @@protoc_insertion_point(field_get:converse.service.link.IdentifyMyselfRequest.port)
  return _internal_port();
}
inline void IdentifyMyselfRequest::set_port(::uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:converse.service.link.IdentifyMyselfRequest.port)
}
inline ::uint32_t IdentifyMyselfRequest::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void IdentifyMyselfRequest::_internal_set_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// -------------------------------------------------------------------

// IdentifyMyselfResponse

// repeated .converse.service.link.ServerAddress cluster_addresses = 1 [json_name = "clusterAddresses"];
inline int IdentifyMyselfResponse::_internal_cluster_addresses_size() const {
  return _internal_cluster_addresses().size();
}
inline int IdentifyMyselfResponse::cluster_addresses_size() const {
  return _internal_cluster_addresses_size();
}
inline void IdentifyMyselfResponse::clear_cluster_addresses() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cluster_addresses_.Clear();
}
inline ::converse::service::link::ServerAddress* IdentifyMyselfResponse::mutable_cluster_addresses(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:converse.service.link.IdentifyMyselfResponse.cluster_addresses)
  return _internal_mutable_cluster_addresses()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>* IdentifyMyselfResponse::mutable_cluster_addresses()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:converse.service.link.IdentifyMyselfResponse.cluster_addresses)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cluster_addresses();
}
inline const ::converse::service::link::ServerAddress& IdentifyMyselfResponse::cluster_addresses(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:converse.service.link.IdentifyMyselfResponse.cluster_addresses)
  return _internal_cluster_addresses().Get(index);
}
inline ::converse::service::link::ServerAddress* IdentifyMyselfResponse::add_cluster_addresses() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::converse::service::link::ServerAddress* _add = _internal_mutable_cluster_addresses()->Add();
  // @@protoc_insertion_point(field_add:converse.service.link.IdentifyMyselfResponse.cluster_addresses)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>& IdentifyMyselfResponse::cluster_addresses() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:converse.service.link.IdentifyMyselfResponse.cluster_addresses)
  return _internal_cluster_addresses();
}
inline const ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>&
IdentifyMyselfResponse::_internal_cluster_addresses() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cluster_addresses_;
}
inline ::google::protobuf::RepeatedPtrField<::converse::service::link::ServerAddress>*
IdentifyMyselfResponse::_internal_mutable_cluster_addresses() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cluster_addresses_;
}

// bytes database = 2 [json_name = "database"];
inline void IdentifyMyselfResponse::clear_database() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.database_.ClearToEmpty();
}
inline const std::string& IdentifyMyselfResponse::database() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:converse.service.link.IdentifyMyselfResponse.database)
  return _internal_database();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void IdentifyMyselfResponse::set_database(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.database_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:converse.service.link.IdentifyMyselfResponse.database)
}
inline std::string* IdentifyMyselfResponse::mutable_database() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_database();
  // @@protoc_insertion_point(field_mutable:converse.service.link.IdentifyMyselfResponse.database)
  return _s;
}
inline const std::string& IdentifyMyselfResponse::_internal_database() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.database_.Get();
}
inline void IdentifyMyselfResponse::_internal_set_database(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.database_.Set(value, GetArena());
}
inline std::string* IdentifyMyselfResponse::_internal_mutable_database() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.database_.Mutable( GetArena());
}
inline std::string* IdentifyMyselfResponse::release_database() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:converse.service.link.IdentifyMyselfResponse.database)
  return _impl_.database_.Release();
}
inline void IdentifyMyselfResponse::set_allocated_database(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.database_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.database_.IsDefault()) {
    _impl_.database_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:converse.service.link.IdentifyMyselfResponse.database)
}

// -------------------------------------------------------------------

// GetTransactionsRequest

// -------------------------------------------------------------------

// GetTransactionsResponse

// uint64 transaction_id = 1 [json_name = "transactionId"];
inline void GetTransactionsResponse::clear_transaction_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transaction_id_ = ::uint64_t{0u};
}
inline ::uint64_t GetTransactionsResponse::transaction_id() const {
  // @@protoc_insertion_point(field_get:converse.service.link.GetTransactionsResponse.transaction_id)
  return _internal_transaction_id();
}
inline void GetTransactionsResponse::set_transaction_id(::uint64_t value) {
  _internal_set_transaction_id(value);
  // @@protoc_insertion_point(field_set:converse.service.link.GetTransactionsResponse.transaction_id)
}
inline ::uint64_t GetTransactionsResponse::_internal_transaction_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.transaction_id_;
}
inline void GetTransactionsResponse::_internal_set_transaction_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.transaction_id_ = value;
}

// repeated .converse.service.link.Operation operations = 2 [json_name = "operations"];
inline int GetTransactionsResponse::_internal_operations_size() const {
  return _internal_operations().size();
}
inline int GetTransactionsResponse::operations_size() const {
  return _internal_operations_size();
}
inline void GetTransactionsResponse::clear_operations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.operations_.Clear();
}
inline ::converse::service::link::Operation* GetTransactionsResponse::mutable_operations(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:converse.service.link.GetTransactionsResponse.operations)
  return _internal_mutable_operations()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::converse::service::link::Operation>* GetTransactionsResponse::mutable_operations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:converse.service.link.GetTransactionsResponse.operations)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_operations();
}
inline const ::converse::service::link::Operation& GetTransactionsResponse::operations(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:converse.service.link.GetTransactionsResponse.operations)
  return _internal_operations().Get(index);
}
inline ::converse::service::link::Operation* GetTransactionsResponse::add_operations() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::converse::service::link::Operation* _add = _internal_mutable_operations()->Add();
  // @@protoc_insertion_point(field_add:converse.service.link.GetTransactionsResponse.operations)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::converse::service::link::Operation>& GetTransactionsResponse::operations() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:converse.service.link.GetTransactionsResponse.operations)
  return _internal_operations();
}
inline const ::google::protobuf::RepeatedPtrField<::converse::service::link::Operation>&
GetTransactionsResponse::_internal_operations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.operations_;
}
inline ::google::protobuf::RepeatedPtrField<::converse::service::link::Operation>*
GetTransactionsResponse::_internal_mutable_operations() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.operations_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Operation

// .converse.service.link.OperationType type = 1 [json_name = "type"];
inline void Operation::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::converse::service::link::OperationType Operation::type() const {
  // @@protoc_insertion_point(field_get:converse.service.link.Operation.type)
  return _internal_type();
}
inline void Operation::set_type(::converse::service::link::OperationType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:converse.service.link.Operation.type)
}
inline ::converse::service::link::OperationType Operation::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::converse::service::link::OperationType>(_impl_.type_);
}
inline void Operation::_internal_set_type(::converse::service::link::OperationType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string table_name = 2 [json_name = "tableName"];
inline void Operation::clear_table_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.table_name_.ClearToEmpty();
}
inline const std::string& Operation::table_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:converse.service.link.Operation.table_name)
  return _internal_table_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Operation::set_table_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.table_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:converse.service.link.Operation.table_name)
}
inline std::string* Operation::mutable_table_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_table_name();
  // @@protoc_insertion_point(field_mutable:converse.service.link.Operation.table_name)
  return _s;
}
inline const std::string& Operation::_internal_table_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.table_name_.Get();
}
inline void Operation::_internal_set_table_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.table_name_.Set(value, GetArena());
}
inline std::string* Operation::_internal_mutable_table_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.table_name_.Mutable( GetArena());
}
inline std::string* Operation::release_table_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:converse.service.link.Operation.table_name)
  return _impl_.table_name_.Release();
}
inline void Operation::set_allocated_table_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.table_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.table_name_.IsDefault()) {
    _impl_.table_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:converse.service.link.Operation.table_name)
}

// map<string, string> new_values = 3 [json_name = "newValues"];
inline int Operation::_internal_new_values_size() const {
  return _internal_new_values().size();
}
inline int Operation::new_values_size() const {
  return _internal_new_values_size();
}
inline void Operation::clear_new_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.new_values_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& Operation::_internal_new_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.new_values_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& Operation::new_values() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:converse.service.link.Operation.new_values)
  return _internal_new_values();
}
inline ::google::protobuf::Map<std::string, std::string>* Operation::_internal_mutable_new_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.new_values_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* Operation::mutable_new_values() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:converse.service.link.Operation.new_values)
  return _internal_mutable_new_values();
}

// map<string, string> old_key_values = 4 [json_name = "oldKeyValues"];
inline int Operation::_internal_old_key_values_size() const {
  return _internal_old_key_values().size();
}
inline int Operation::old_key_values_size() const {
  return _internal_old_key_values_size();
}
inline void Operation::clear_old_key_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.old_key_values_.Clear();
}
inline const ::google::protobuf::Map<std::string, std::string>& Operation::_internal_old_key_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.old_key_values_.GetMap();
}
inline const ::google::protobuf::Map<std::string, std::string>& Operation::old_key_values() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:converse.service.link.Operation.old_key_values)
  return _internal_old_key_values();
}
inline ::google::protobuf::Map<std::string, std::string>* Operation::_internal_mutable_old_key_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.old_key_values_.MutableMap();
}
inline ::google::protobuf::Map<std::string, std::string>* Operation::mutable_old_key_values() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:converse.service.link.Operation.old_key_values)
  return _internal_mutable_old_key_values();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace link
}  // namespace service
}  // namespace converse


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::converse::service::link::OperationType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::converse::service::link::OperationType>() {
  return ::converse::service::link::OperationType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // converse_2fservice_2flink_2flink_2eproto_2epb_2eh
