// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: converse/service/link/link.proto
#ifndef GRPC_converse_2fservice_2flink_2flink_2eproto__INCLUDED
#define GRPC_converse_2fservice_2flink_2flink_2eproto__INCLUDED

#include "converse/service/link/link.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace converse {
namespace service {
namespace link {

class LinkService final {
 public:
  static constexpr char const* service_full_name() {
    return "converse.service.link.LinkService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::converse::service::link::GetServersResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::GetServersResponse>> AsyncGetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::GetServersResponse>>(AsyncGetServersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::GetServersResponse>> PrepareAsyncGetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::GetServersResponse>>(PrepareAsyncGetServersRaw(context, request, cq));
    }
    virtual ::grpc::Status IdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::converse::service::link::IdentifyMyselfResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::IdentifyMyselfResponse>> AsyncIdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::IdentifyMyselfResponse>>(AsyncIdentifyMyselfRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::IdentifyMyselfResponse>> PrepareAsyncIdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::IdentifyMyselfResponse>>(PrepareAsyncIdentifyMyselfRaw(context, request, cq));
    }
    virtual ::grpc::Status ClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::converse::service::link::ClaimServerIdResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ClaimServerIdResponse>> AsyncClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ClaimServerIdResponse>>(AsyncClaimServerIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ClaimServerIdResponse>> PrepareAsyncClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ClaimServerIdResponse>>(PrepareAsyncClaimServerIdRaw(context, request, cq));
    }
    virtual ::grpc::Status ReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::converse::service::link::ReplicateTransactionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ReplicateTransactionResponse>> AsyncReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ReplicateTransactionResponse>>(AsyncReplicateTransactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ReplicateTransactionResponse>> PrepareAsyncReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ReplicateTransactionResponse>>(PrepareAsyncReplicateTransactionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest* request, ::converse::service::link::GetServersResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest* request, ::converse::service::link::GetServersResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void IdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest* request, ::converse::service::link::IdentifyMyselfResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void IdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest* request, ::converse::service::link::IdentifyMyselfResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest* request, ::converse::service::link::ClaimServerIdResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest* request, ::converse::service::link::ClaimServerIdResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest* request, ::converse::service::link::ReplicateTransactionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest* request, ::converse::service::link::ReplicateTransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::GetServersResponse>* AsyncGetServersRaw(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::GetServersResponse>* PrepareAsyncGetServersRaw(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::IdentifyMyselfResponse>* AsyncIdentifyMyselfRaw(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::IdentifyMyselfResponse>* PrepareAsyncIdentifyMyselfRaw(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ClaimServerIdResponse>* AsyncClaimServerIdRaw(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ClaimServerIdResponse>* PrepareAsyncClaimServerIdRaw(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ReplicateTransactionResponse>* AsyncReplicateTransactionRaw(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::converse::service::link::ReplicateTransactionResponse>* PrepareAsyncReplicateTransactionRaw(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::converse::service::link::GetServersResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::GetServersResponse>> AsyncGetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::GetServersResponse>>(AsyncGetServersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::GetServersResponse>> PrepareAsyncGetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::GetServersResponse>>(PrepareAsyncGetServersRaw(context, request, cq));
    }
    ::grpc::Status IdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::converse::service::link::IdentifyMyselfResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::IdentifyMyselfResponse>> AsyncIdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::IdentifyMyselfResponse>>(AsyncIdentifyMyselfRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::IdentifyMyselfResponse>> PrepareAsyncIdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::IdentifyMyselfResponse>>(PrepareAsyncIdentifyMyselfRaw(context, request, cq));
    }
    ::grpc::Status ClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::converse::service::link::ClaimServerIdResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::ClaimServerIdResponse>> AsyncClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::ClaimServerIdResponse>>(AsyncClaimServerIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::ClaimServerIdResponse>> PrepareAsyncClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::ClaimServerIdResponse>>(PrepareAsyncClaimServerIdRaw(context, request, cq));
    }
    ::grpc::Status ReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::converse::service::link::ReplicateTransactionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::ReplicateTransactionResponse>> AsyncReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::ReplicateTransactionResponse>>(AsyncReplicateTransactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::ReplicateTransactionResponse>> PrepareAsyncReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::converse::service::link::ReplicateTransactionResponse>>(PrepareAsyncReplicateTransactionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest* request, ::converse::service::link::GetServersResponse* response, std::function<void(::grpc::Status)>) override;
      void GetServers(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest* request, ::converse::service::link::GetServersResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void IdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest* request, ::converse::service::link::IdentifyMyselfResponse* response, std::function<void(::grpc::Status)>) override;
      void IdentifyMyself(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest* request, ::converse::service::link::IdentifyMyselfResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest* request, ::converse::service::link::ClaimServerIdResponse* response, std::function<void(::grpc::Status)>) override;
      void ClaimServerId(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest* request, ::converse::service::link::ClaimServerIdResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest* request, ::converse::service::link::ReplicateTransactionResponse* response, std::function<void(::grpc::Status)>) override;
      void ReplicateTransaction(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest* request, ::converse::service::link::ReplicateTransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::converse::service::link::GetServersResponse>* AsyncGetServersRaw(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::converse::service::link::GetServersResponse>* PrepareAsyncGetServersRaw(::grpc::ClientContext* context, const ::converse::service::link::GetServersRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::converse::service::link::IdentifyMyselfResponse>* AsyncIdentifyMyselfRaw(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::converse::service::link::IdentifyMyselfResponse>* PrepareAsyncIdentifyMyselfRaw(::grpc::ClientContext* context, const ::converse::service::link::IdentifyMyselfRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::converse::service::link::ClaimServerIdResponse>* AsyncClaimServerIdRaw(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::converse::service::link::ClaimServerIdResponse>* PrepareAsyncClaimServerIdRaw(::grpc::ClientContext* context, const ::converse::service::link::ClaimServerIdRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::converse::service::link::ReplicateTransactionResponse>* AsyncReplicateTransactionRaw(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::converse::service::link::ReplicateTransactionResponse>* PrepareAsyncReplicateTransactionRaw(::grpc::ClientContext* context, const ::converse::service::link::ReplicateTransactionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetServers_;
    const ::grpc::internal::RpcMethod rpcmethod_IdentifyMyself_;
    const ::grpc::internal::RpcMethod rpcmethod_ClaimServerId_;
    const ::grpc::internal::RpcMethod rpcmethod_ReplicateTransaction_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetServers(::grpc::ServerContext* context, const ::converse::service::link::GetServersRequest* request, ::converse::service::link::GetServersResponse* response);
    virtual ::grpc::Status IdentifyMyself(::grpc::ServerContext* context, const ::converse::service::link::IdentifyMyselfRequest* request, ::converse::service::link::IdentifyMyselfResponse* response);
    virtual ::grpc::Status ClaimServerId(::grpc::ServerContext* context, const ::converse::service::link::ClaimServerIdRequest* request, ::converse::service::link::ClaimServerIdResponse* response);
    virtual ::grpc::Status ReplicateTransaction(::grpc::ServerContext* context, const ::converse::service::link::ReplicateTransactionRequest* request, ::converse::service::link::ReplicateTransactionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetServers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetServers() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetServers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServers(::grpc::ServerContext* /*context*/, const ::converse::service::link::GetServersRequest* /*request*/, ::converse::service::link::GetServersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServers(::grpc::ServerContext* context, ::converse::service::link::GetServersRequest* request, ::grpc::ServerAsyncResponseWriter< ::converse::service::link::GetServersResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_IdentifyMyself : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_IdentifyMyself() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_IdentifyMyself() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyMyself(::grpc::ServerContext* /*context*/, const ::converse::service::link::IdentifyMyselfRequest* /*request*/, ::converse::service::link::IdentifyMyselfResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIdentifyMyself(::grpc::ServerContext* context, ::converse::service::link::IdentifyMyselfRequest* request, ::grpc::ServerAsyncResponseWriter< ::converse::service::link::IdentifyMyselfResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ClaimServerId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ClaimServerId() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ClaimServerId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimServerId(::grpc::ServerContext* /*context*/, const ::converse::service::link::ClaimServerIdRequest* /*request*/, ::converse::service::link::ClaimServerIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClaimServerId(::grpc::ServerContext* context, ::converse::service::link::ClaimServerIdRequest* request, ::grpc::ServerAsyncResponseWriter< ::converse::service::link::ClaimServerIdResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReplicateTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReplicateTransaction() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ReplicateTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReplicateTransaction(::grpc::ServerContext* /*context*/, const ::converse::service::link::ReplicateTransactionRequest* /*request*/, ::converse::service::link::ReplicateTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReplicateTransaction(::grpc::ServerContext* context, ::converse::service::link::ReplicateTransactionRequest* request, ::grpc::ServerAsyncResponseWriter< ::converse::service::link::ReplicateTransactionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetServers<WithAsyncMethod_IdentifyMyself<WithAsyncMethod_ClaimServerId<WithAsyncMethod_ReplicateTransaction<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetServers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetServers() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::converse::service::link::GetServersRequest, ::converse::service::link::GetServersResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::converse::service::link::GetServersRequest* request, ::converse::service::link::GetServersResponse* response) { return this->GetServers(context, request, response); }));}
    void SetMessageAllocatorFor_GetServers(
        ::grpc::MessageAllocator< ::converse::service::link::GetServersRequest, ::converse::service::link::GetServersResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::converse::service::link::GetServersRequest, ::converse::service::link::GetServersResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetServers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServers(::grpc::ServerContext* /*context*/, const ::converse::service::link::GetServersRequest* /*request*/, ::converse::service::link::GetServersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetServers(
      ::grpc::CallbackServerContext* /*context*/, const ::converse::service::link::GetServersRequest* /*request*/, ::converse::service::link::GetServersResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_IdentifyMyself : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_IdentifyMyself() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::converse::service::link::IdentifyMyselfRequest, ::converse::service::link::IdentifyMyselfResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::converse::service::link::IdentifyMyselfRequest* request, ::converse::service::link::IdentifyMyselfResponse* response) { return this->IdentifyMyself(context, request, response); }));}
    void SetMessageAllocatorFor_IdentifyMyself(
        ::grpc::MessageAllocator< ::converse::service::link::IdentifyMyselfRequest, ::converse::service::link::IdentifyMyselfResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::converse::service::link::IdentifyMyselfRequest, ::converse::service::link::IdentifyMyselfResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_IdentifyMyself() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyMyself(::grpc::ServerContext* /*context*/, const ::converse::service::link::IdentifyMyselfRequest* /*request*/, ::converse::service::link::IdentifyMyselfResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IdentifyMyself(
      ::grpc::CallbackServerContext* /*context*/, const ::converse::service::link::IdentifyMyselfRequest* /*request*/, ::converse::service::link::IdentifyMyselfResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ClaimServerId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ClaimServerId() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::converse::service::link::ClaimServerIdRequest, ::converse::service::link::ClaimServerIdResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::converse::service::link::ClaimServerIdRequest* request, ::converse::service::link::ClaimServerIdResponse* response) { return this->ClaimServerId(context, request, response); }));}
    void SetMessageAllocatorFor_ClaimServerId(
        ::grpc::MessageAllocator< ::converse::service::link::ClaimServerIdRequest, ::converse::service::link::ClaimServerIdResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::converse::service::link::ClaimServerIdRequest, ::converse::service::link::ClaimServerIdResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ClaimServerId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimServerId(::grpc::ServerContext* /*context*/, const ::converse::service::link::ClaimServerIdRequest* /*request*/, ::converse::service::link::ClaimServerIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ClaimServerId(
      ::grpc::CallbackServerContext* /*context*/, const ::converse::service::link::ClaimServerIdRequest* /*request*/, ::converse::service::link::ClaimServerIdResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReplicateTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReplicateTransaction() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::converse::service::link::ReplicateTransactionRequest, ::converse::service::link::ReplicateTransactionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::converse::service::link::ReplicateTransactionRequest* request, ::converse::service::link::ReplicateTransactionResponse* response) { return this->ReplicateTransaction(context, request, response); }));}
    void SetMessageAllocatorFor_ReplicateTransaction(
        ::grpc::MessageAllocator< ::converse::service::link::ReplicateTransactionRequest, ::converse::service::link::ReplicateTransactionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::converse::service::link::ReplicateTransactionRequest, ::converse::service::link::ReplicateTransactionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReplicateTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReplicateTransaction(::grpc::ServerContext* /*context*/, const ::converse::service::link::ReplicateTransactionRequest* /*request*/, ::converse::service::link::ReplicateTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReplicateTransaction(
      ::grpc::CallbackServerContext* /*context*/, const ::converse::service::link::ReplicateTransactionRequest* /*request*/, ::converse::service::link::ReplicateTransactionResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetServers<WithCallbackMethod_IdentifyMyself<WithCallbackMethod_ClaimServerId<WithCallbackMethod_ReplicateTransaction<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetServers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetServers() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetServers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServers(::grpc::ServerContext* /*context*/, const ::converse::service::link::GetServersRequest* /*request*/, ::converse::service::link::GetServersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_IdentifyMyself : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_IdentifyMyself() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_IdentifyMyself() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyMyself(::grpc::ServerContext* /*context*/, const ::converse::service::link::IdentifyMyselfRequest* /*request*/, ::converse::service::link::IdentifyMyselfResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ClaimServerId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ClaimServerId() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ClaimServerId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimServerId(::grpc::ServerContext* /*context*/, const ::converse::service::link::ClaimServerIdRequest* /*request*/, ::converse::service::link::ClaimServerIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReplicateTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReplicateTransaction() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ReplicateTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReplicateTransaction(::grpc::ServerContext* /*context*/, const ::converse::service::link::ReplicateTransactionRequest* /*request*/, ::converse::service::link::ReplicateTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetServers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetServers() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetServers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServers(::grpc::ServerContext* /*context*/, const ::converse::service::link::GetServersRequest* /*request*/, ::converse::service::link::GetServersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_IdentifyMyself : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_IdentifyMyself() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_IdentifyMyself() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyMyself(::grpc::ServerContext* /*context*/, const ::converse::service::link::IdentifyMyselfRequest* /*request*/, ::converse::service::link::IdentifyMyselfResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIdentifyMyself(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ClaimServerId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ClaimServerId() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ClaimServerId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimServerId(::grpc::ServerContext* /*context*/, const ::converse::service::link::ClaimServerIdRequest* /*request*/, ::converse::service::link::ClaimServerIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestClaimServerId(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReplicateTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReplicateTransaction() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ReplicateTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReplicateTransaction(::grpc::ServerContext* /*context*/, const ::converse::service::link::ReplicateTransactionRequest* /*request*/, ::converse::service::link::ReplicateTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReplicateTransaction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetServers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetServers() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetServers(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetServers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServers(::grpc::ServerContext* /*context*/, const ::converse::service::link::GetServersRequest* /*request*/, ::converse::service::link::GetServersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetServers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_IdentifyMyself : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_IdentifyMyself() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->IdentifyMyself(context, request, response); }));
    }
    ~WithRawCallbackMethod_IdentifyMyself() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status IdentifyMyself(::grpc::ServerContext* /*context*/, const ::converse::service::link::IdentifyMyselfRequest* /*request*/, ::converse::service::link::IdentifyMyselfResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* IdentifyMyself(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ClaimServerId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ClaimServerId() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ClaimServerId(context, request, response); }));
    }
    ~WithRawCallbackMethod_ClaimServerId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ClaimServerId(::grpc::ServerContext* /*context*/, const ::converse::service::link::ClaimServerIdRequest* /*request*/, ::converse::service::link::ClaimServerIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ClaimServerId(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReplicateTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReplicateTransaction() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReplicateTransaction(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReplicateTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReplicateTransaction(::grpc::ServerContext* /*context*/, const ::converse::service::link::ReplicateTransactionRequest* /*request*/, ::converse::service::link::ReplicateTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReplicateTransaction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetServers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetServers() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::converse::service::link::GetServersRequest, ::converse::service::link::GetServersResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::converse::service::link::GetServersRequest, ::converse::service::link::GetServersResponse>* streamer) {
                       return this->StreamedGetServers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetServers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetServers(::grpc::ServerContext* /*context*/, const ::converse::service::link::GetServersRequest* /*request*/, ::converse::service::link::GetServersResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetServers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::converse::service::link::GetServersRequest,::converse::service::link::GetServersResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_IdentifyMyself : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_IdentifyMyself() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::converse::service::link::IdentifyMyselfRequest, ::converse::service::link::IdentifyMyselfResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::converse::service::link::IdentifyMyselfRequest, ::converse::service::link::IdentifyMyselfResponse>* streamer) {
                       return this->StreamedIdentifyMyself(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_IdentifyMyself() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status IdentifyMyself(::grpc::ServerContext* /*context*/, const ::converse::service::link::IdentifyMyselfRequest* /*request*/, ::converse::service::link::IdentifyMyselfResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIdentifyMyself(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::converse::service::link::IdentifyMyselfRequest,::converse::service::link::IdentifyMyselfResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ClaimServerId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ClaimServerId() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::converse::service::link::ClaimServerIdRequest, ::converse::service::link::ClaimServerIdResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::converse::service::link::ClaimServerIdRequest, ::converse::service::link::ClaimServerIdResponse>* streamer) {
                       return this->StreamedClaimServerId(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ClaimServerId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ClaimServerId(::grpc::ServerContext* /*context*/, const ::converse::service::link::ClaimServerIdRequest* /*request*/, ::converse::service::link::ClaimServerIdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedClaimServerId(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::converse::service::link::ClaimServerIdRequest,::converse::service::link::ClaimServerIdResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReplicateTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReplicateTransaction() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::converse::service::link::ReplicateTransactionRequest, ::converse::service::link::ReplicateTransactionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::converse::service::link::ReplicateTransactionRequest, ::converse::service::link::ReplicateTransactionResponse>* streamer) {
                       return this->StreamedReplicateTransaction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReplicateTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReplicateTransaction(::grpc::ServerContext* /*context*/, const ::converse::service::link::ReplicateTransactionRequest* /*request*/, ::converse::service::link::ReplicateTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReplicateTransaction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::converse::service::link::ReplicateTransactionRequest,::converse::service::link::ReplicateTransactionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetServers<WithStreamedUnaryMethod_IdentifyMyself<WithStreamedUnaryMethod_ClaimServerId<WithStreamedUnaryMethod_ReplicateTransaction<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetServers<WithStreamedUnaryMethod_IdentifyMyself<WithStreamedUnaryMethod_ClaimServerId<WithStreamedUnaryMethod_ReplicateTransaction<Service > > > > StreamedService;
};

}  // namespace link
}  // namespace service
}  // namespace converse


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_converse_2fservice_2flink_2flink_2eproto__INCLUDED
