name: mousedb-client
services:
  shell:
    build: .
    environment:
      - TERM
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - .:/code
      - root:/root

volumes:
  root:
